insert into category (name) value ('Keramika');
insert into category (name) value ('Gintaras');
insert into category (name) value ('Oda');
insert into category (name) value ('Tekstile');
insert into category (name, parent_id) value ('Puodynes', 1);
insert into category (name, parent_id) value ('Karoliai', 2);
insert into category (name, parent_id) value ('Marskiniai', 4);
insert into category (name, parent_id) value ('Ąsočiai', 1);
insert into category (name, parent_id) value ('Puodeliai', 1);
insert into category (name, parent_id) value ('Puodziukai', 1);
insert into category (name, parent_id) value ('Apyrankės', 3);
insert into category (name, parent_id) value ('Dirželiai', 3);
insert into category (name, parent_id) value ('Paveikslai', 2);
insert into category (name, parent_id) value ('Staltiesė', 4);
